# Site settings
title: B.S. in Applied Science at UW-Stout
email: pattersonm@uwstout.edu
description: > # this means to ignore newlines until "baseurl:"
     B.S. in Applied Science \\
     University of Wisconsin - Stout \\
     Posted work is licensed under a Creative Commons BY-NC-SA 4.0 License unless noted
	otherwise.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://AppliedScienceProgram.github.io" # the base hostname & protocol for your site
# twitter_username: twitternamehere
github_username:  AppliedScienceProgram	

# Build settings
markdown: kramdown
